default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: expess_development
  username: postgres
  password: 
  host: localhost

test:
  <<: *default
  database: expess_test
  username: postgres
  password: 
  host: localhost
